### ISSUE TITLE
Proton_dist.tar.gz is missing

### ISSUE THREAD

**Issue by ghost** [popsUlfr/Proton#9]
* Version: Proton 3.16-6 Gallium Nine Extras 0.1.2 _(pre-built tar.gz downloaded from the releases tab)_
I am unable to start any game and Steam yields output:
```
Traceback (most recent call last):
  File "/home/user/.var/app/com.valvesoftware.Steam/.local/share/Steam/compatibilitytools.d/Proton_3.16-6_Gallium_Nine_Extras_0.1.2/proton", line 159, in <module>
    tar = tarfile.open(basedir + "/proton_dist.tar.gz", mode="r:gz")
  File "/usr/lib/python3.7/tarfile.py", line 1589, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python3.7/tarfile.py", line 1636, in gzopen
    fileobj = gzip.GzipFile(name, mode + "b", compresslevel, fileobj)
  File "/usr/lib/python3.7/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.var/app/com.valvesoftware.Steam/.local/share/Steam/compatibilitytools.d/Proton_3.16-6_Gallium_Nine_Extras_0.1.2/proton_dist.tar.gz'
```

**Comment by popsUlfr** [comment]
Oh the `version` file got updated which pushes Steam to just nuke the `dist` folder.
I updated the build on the release page : https://github.com/popsUlfr/Proton/releases/tag/proton-3.16-6-gne-0.1.2

Very sorry about this :/

Checksums : 
```
sha256 32d3cecdc547c05c708145fcfb111d5feccc5132ea0e46ce15901cb0ee80bcd9  Proton_3.16-6_Gallium_Nine_Extras_0.1.2.tar.xz
```

**The old one was** : 
```
sha256 a96b68f20f87960188aa9de41ecfe03204f3260764856568c3e32a53c0ea1033  Proton_3.16-6_Gallium_Nine_Extras_0.1.2.tar.xz
```

**Comment by ghost** [comment]
The error is no longer present. Thank you!
